//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.ReceivedPackage = new HashSet<ReceivedPackage>();
            this.ReceivedPackage1 = new HashSet<ReceivedPackage>();
            this.SentPackage = new HashSet<SentPackage>();
            this.SentPackage1 = new HashSet<SentPackage>();
            this.Subscribe = new HashSet<Subscribe>();
        }

        public Clients(string f, string n, string l, string i, string a)
        {
            this.ReceivedPackage = new HashSet<ReceivedPackage>();
            this.ReceivedPackage1 = new HashSet<ReceivedPackage>();
            this.SentPackage = new HashSet<SentPackage>();
            this.SentPackage1 = new HashSet<SentPackage>();
            this.Subscribe = new HashSet<Subscribe>();
            IDCLIENT = f + " " + n[0] + "." + l[0] + ".";
            CLIENT = f + n + l;
            INDEX = Convert.ToInt32(i);
            ADDRES = a;
        }
        public string IDCLIENT { get; set; }
        public string CLIENT { get; set; }
        public Nullable<int> INDEX { get; set; }
        public string ADDRES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivedPackage> ReceivedPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivedPackage> ReceivedPackage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SentPackage> SentPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SentPackage> SentPackage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscribe> Subscribe { get; set; }
        public virtual INDEX INDEX1 { get; set; }
    }
}
