//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostOffices
    {
        public string OFFICE { get; set; }
        public string IDOFFICE { get; set; }
        public Nullable<int> INDEX { get; set; }
    
        public virtual INDEX INDEX1 { get; set; }
    }
}
