//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSTContext : DbContext
    {
        public POSTContext()
            : base("name=POSTContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Edition> Edition { get; set; }
        public virtual DbSet<INDEX> INDEX { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<PostOffices> PostOffices { get; set; }
        public virtual DbSet<ReceivedPackage> ReceivedPackage { get; set; }
        public virtual DbSet<SentPackage> SentPackage { get; set; }
        public virtual DbSet<StatusPack> StatusPack { get; set; }
        public virtual DbSet<Subscribe> Subscribe { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
